apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-redis
  namespace: checkout
  labels:
    app.kubernetes.io/name: checkout-redis
    app.kubernetes.io/component: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: checkout-redis
      app.kubernetes.io/component: deployment
  template:
    metadata:
      labels:
        app.kubernetes.io/name: checkout-redis
        app.kubernetes.io/component: deployment
    spec:
      containers:
        - name: redis
          image: "redis:6.0-alpine"
          imagePullPolicy: IfNotPresent
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP