apiVersion: v1
kind: Service
metadata:
  name: checkout-redis
  namespace: checkout
  labels:
    app.kubernetes.io/name: checkout-redis
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: checkout-redis
    app.kubernetes.io/component: deployment