apiVersion: v1
kind: ConfigMap
metadata:
  name: ui
  namespace: ui
data:
  ENDPOINTS_CATALOG: "http://catalog.catalog:80"
  ENDPOINTS_ASSETS: "http://assets.assets:80"
  ENDPOINTS_CHECKOUT: "http://checkout.checkout:80"