apiVersion: v1
kind: Pod
metadata:
  name: "ui-test-connection"
  namespace: ui
  labels:
    app.kubernetes.io/name: ui
    app.kubernetes.io/component: service
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['ui.ui:80']
  restartPolicy: Always