apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: kind-cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30001
        hostPort: 8000
        listenAddress: "127.0.0.1"
        protocol: TCP