apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configMap.yaml
  - serviceAccount.yaml
  - roles/ReadDeployments
  - redis
  - deployment.yaml
  - service.yaml
  - testConnection.yaml